spring:
  data:
    mongodb:
      uri: '{encrypt}AQA8WxhzYtiRyrGuSBV17fw2u2ZYpOA6hrWdrhQZjEq2M4VMMC8qIRZjQJN2YzoxbKhwnG8zK7C0lQaQA/0JSnnWlXkX1S+UTwLhmYSyIrHtG6lHbUUSvonhqKjy74r0kwG38hQT3SLH9MdgnW2Sk0AeYZIJwF/THudtTbDhQRbJs0TQaOfk80yS8wIoKOGt5ebmKTav39xW5vPvEBmUE8KQo0M5vdRuh03KZbrI2q5oejYxRY1c3OImxhVlik3cGXfnMTlYZervO57w+DXZ6bggmhlB1PthZ8uIrjZT+gs1BpsiCJKRe+rn7ok/plxGanCZNgOc1QiZbYFUvZHUpFGIgrJQYYXzfLYbwRRf1a4etzNqXZ0PNDGCw0Y94xLzAMF4fzWnS52Mm+w4f3YDEgiVlZlUHy2jgqQ6wbtH1KeCQPn3l8Gy+ksW8SRAIa8PBnNzMpMKsOeSukeJphWSgTdmW6yTCXlIQOkZaHoILSx2RA=='
